services:
  - type: web
    name: patientor
    runtime: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
